"""add_scheduling_persist_columns

Revision ID: 318404aba419
Revises: 0ea3133e3615
Create Date: 2026-05-22 11:15:59.292489

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "318404aba419"
down_revision: Union[str, Sequence[str], None] = "0ea3133e3615"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Guards: initial migration now creates all tables via create_all(),
    # so columns may already exist on fresh databases.
    from alembic import op as _op

    conn = _op.get_bind()
    inspector = sa.inspect(conn)
    commitments_cols = {c["name"] for c in inspector.get_columns("commitments")}
    settings_cols = {c["name"] for c in inspector.get_columns("user_settings")}
    if "last_reminded_at" not in commitments_cols:
        op.add_column(
            "commitments", sa.Column("last_reminded_at", sa.DateTime(), nullable=True)
        )
    if "proactive_last_sent" not in settings_cols:
        op.add_column(
            "user_settings",
            sa.Column("proactive_last_sent", sa.DateTime(), nullable=True),
        )
    if "habit_last_run_date" not in settings_cols:
        op.add_column(
            "user_settings", sa.Column("habit_last_run_date", sa.Date(), nullable=True)
        )
    if "llm_provider" in settings_cols:
        pass  # create_all() already creates with String(24); SQLite can't ALTER COLUMN natively
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ALTER COLUMN skipped — SQLite can't do it natively. No-op.
    op.drop_column("user_settings", "habit_last_run_date")
    op.drop_column("user_settings", "proactive_last_sent")
    op.drop_column("commitments", "last_reminded_at")
    # ### end Alembic commands ###
