"""Database repository — thin re-export from domain modules."""

from __future__ import annotations

# Re-export everything from domain modules
from src.db.repos.session_repo import (
    count_new_personal_facts_since,
    delete_telegram_session,
    get_or_create_user,
    get_persona,
    get_self_profile,
    load_telegram_session,
    save_telegram_session,
    search_session_messages,
    update_persona,
    upsert_self_profile,
)

from src.db.repos.key_repo import (
    add_key_slot,
    get_active_keys,
    get_api_key,
    get_api_keys,
    list_key_slots,
    mark_key_failure,
    mark_key_used,
    upsert_api_key,
)

from src.db.repos.contact_repo import (
    add_allowed_contact,
    add_watched_peer,
    get_contact,
    get_contact_profile,
    get_watched_peers,
    is_contact_allowed,
    is_peer_watched,
    list_contact_profiles,
    list_contacts,
    list_folders,
    remove_allowed_contact,
    remove_watched_peer,
    set_news_source,
    upsert_contact,
    upsert_contact_profile,
    upsert_folders,
)

from src.db.repos.message_repo import (
    add_auto_reply_log,
    cache_transcript,
    count_messages,
    fetch_chat_messages,
    fetch_my_messages_global,
    fetch_my_messages_in_chat,
    get_cached_transcript,
    get_conversation_state,
    list_active_conversations,
    list_recent_auto_replies,
    upsert_conversation_state,
    upsert_message,
)

from src.db.repos.memory_repo import (
    FtsHit,
    add_member,
    add_memory,
    add_memory_candidate,
    cross_chat_search,
    delete_memory,
    delete_memory_candidate,
    find_similar_memories,
    fts_search,
    get_cluster_members,
    get_graph_stats,
    get_linked_memories,
    get_memory_graph,
    get_memory_stats,
    link_memories,
    contact_impact,
    list_clusters_for_contact,
    list_memories,
    list_memory_candidates,
    list_memory_clusters,
    search_memories,
    search_memories_fts,
    search_memories_fts_with_scores,
    unlink_memories,
    upsert_memory_cluster,
)

from src.db.repos.commitment_repo import (
    add_commitment,
    add_pending_question,
    create_pending_action,
    delete_pending_action,
    get_commitment,
    get_commitment_by_source_memory,
    get_pending_action,
    get_pending_questions,
    list_open_commitments,
    update_commitment_status,
)

from src.db.repos.skill_repo import (
    add_skill_usage,
    add_trajectory,
    get_skill_by_name,
    list_skills,
    list_trajectories,
    set_skill_enabled,
    upsert_skill,
)

from src.db.repos.cache_repo import (
    get_agent_cache,
    upsert_agent_cache,
)

from src.db.repos.news_repo import (
    add_news_topic,
    delete_news_topic,
    list_news_topics,
    toggle_news_topic,
)

from src.db.repos.scheduled_repo import (
    create_scheduled,
    get_pending,
    get_user_pending,
    mark_failed,
    mark_sent,
)

__all__ = [
    # session
    "count_new_personal_facts_since",
    "delete_telegram_session",
    "get_or_create_user",
    "get_persona",
    "get_self_profile",
    "load_telegram_session",
    "save_telegram_session",
    "search_session_messages",
    "update_persona",
    "upsert_self_profile",
    # keys
    "add_key_slot",
    "get_active_keys",
    "get_api_key",
    "get_api_keys",
    "list_key_slots",
    "mark_key_failure",
    "mark_key_used",
    "upsert_api_key",
    # contacts
    "add_allowed_contact",
    "add_watched_peer",
    "get_contact",
    "get_contact_profile",
    "get_watched_peers",
    "is_contact_allowed",
    "is_peer_watched",
    "list_contact_profiles",
    "list_contacts",
    "list_folders",
    "remove_allowed_contact",
    "remove_watched_peer",
    "set_news_source",
    "upsert_contact",
    "upsert_contact_profile",
    "upsert_folders",
    # messages
    "add_auto_reply_log",
    "cache_transcript",
    "count_messages",
    "fetch_chat_messages",
    "fetch_my_messages_global",
    "fetch_my_messages_in_chat",
    "get_cached_transcript",
    "get_conversation_state",
    "list_active_conversations",
    "list_recent_auto_replies",
    "upsert_conversation_state",
    "upsert_message",
    # memory
    "FtsHit",
    "add_member",
    "add_memory",
    "add_memory_candidate",
    "cross_chat_search",
    "delete_memory",
    "delete_memory_candidate",
    "find_similar_memories",
    "fts_search",
    "get_cluster_members",
    "get_graph_stats",
    "get_linked_memories",
    "get_memory_graph",
    "get_memory_stats",
    "link_memories",
    "contact_impact",
    "list_clusters_for_contact",
    "list_memories",
    "list_memory_candidates",
    "list_memory_clusters",
    "search_memories",
    "search_memories_fts",
    "search_memories_fts_with_scores",
    "unlink_memories",
    "upsert_memory_cluster",
    # commitments
    "add_commitment",
    "add_pending_question",
    "create_pending_action",
    "delete_pending_action",
    "get_commitment",
    "get_commitment_by_source_memory",
    "get_pending_action",
    "get_pending_questions",
    "list_open_commitments",
    "update_commitment_status",
    # skills
    "add_skill_usage",
    "add_trajectory",
    "get_skill_by_name",
    "list_skills",
    "list_trajectories",
    "set_skill_enabled",
    "upsert_skill",
    # cache
    "get_agent_cache",
    "upsert_agent_cache",
    # news
    "add_news_topic",
    "delete_news_topic",
    "list_news_topics",
    "toggle_news_topic",
    # scheduled
    "create_scheduled",
    "get_pending",
    "get_user_pending",
    "mark_failed",
    "mark_sent",
]
